### ISSUE TITLE
Performance issues

### ISSUE THREAD

**Issue by romainmenke** [stevenle/topsort#2]
Hi,

Just wanted to let you know that I tried this package and found that it has poor performance.
Maybe this is ok :)

**Comment by stevenle** [comment]
this was written in 2013 when i was first experimenting with golang so i'm not surprised if there are performance problems, there are probably better ways to implement it now. i'm happy to review any pull requests if you have suggestions to improve performance, otherwise i'd suggest looking at other people's packages as they may be better maintained than this one.

**Comment by romainmenke** [comment]
Ended up using [github.com/philopon/go-toposort](https://github.com/philopon/go-toposort)
Closing this :)
